/**
 * Generate a CSS custom properties file from parseStyle() output.
 * @param {object} parsed - Output from parseStyle()
 * @returns {string} CSS file content
 */
export function generateCss(parsed) {
  const lines = [];
  lines.push(`/* ${parsed.title || parsed.name} — Generated by designbrief */`);
  lines.push('');
  lines.push(':root {');

  let hasTokens = false;

  // Colors
  const colorEntries = Object.entries(parsed.colors).filter(([k]) => !k.startsWith('_'));
  if (colorEntries.length > 0) {
    lines.push('  /* Colors */');
    for (const [role, value] of colorEntries) {
      lines.push(`  --color-${camelToKebab(role)}: ${value};`);
    }
    hasTokens = true;
  }

  // Fonts
  const fontEntries = Object.entries(parsed.fonts);
  if (fontEntries.length > 0) {
    if (hasTokens) lines.push('');
    lines.push('  /* Fonts */');
    for (const [role, stack] of fontEntries) {
      const value = stack.map(quoteFontName).join(', ');
      lines.push(`  --font-${role}: ${value};`);
    }
    hasTokens = true;
  }

  // Border radius
  if (parsed.radii.length > 0) {
    if (hasTokens) lines.push('');
    lines.push('  /* Border Radius */');
    if (parsed.radii.length === 1) {
      lines.push(`  --radius: ${parsed.radii[0]};`);
    } else {
      lines.push(`  --radius-sm: ${parsed.radii[0]};`);
      lines.push(`  --radius: ${parsed.radii[Math.floor(parsed.radii.length / 2)]};`);
      lines.push(`  --radius-lg: ${parsed.radii[parsed.radii.length - 1]};`);
    }
    hasTokens = true;
  }

  // Shadows
  if (parsed.shadows.length > 0) {
    if (hasTokens) lines.push('');
    lines.push('  /* Shadows */');
    parsed.shadows.forEach((s, i) => {
      const key = i === 0 ? 'shadow' : `shadow-lg`;
      lines.push(`  --${key}: ${s};`);
    });
    hasTokens = true;
  }

  // Transitions
  if (parsed.transitions.durations.length > 0 || parsed.transitions.easings.length > 0) {
    if (hasTokens) lines.push('');
    lines.push('  /* Transitions */');
    if (parsed.transitions.durations.length > 0) {
      lines.push(`  --transition-duration: ${parsed.transitions.durations[0]};`);
    }
    if (parsed.transitions.easings.length > 0) {
      lines.push(`  --transition-easing: ${parsed.transitions.easings[0]};`);
    }
    hasTokens = true;
  }

  lines.push('}');

  // Dark mode
  const darkEntries = Object.entries(parsed.darkColors).filter(([k]) => !k.startsWith('_'));
  if (darkEntries.length > 0 && !parsed.darkColors._extracted) {
    lines.push('');
    lines.push('@media (prefers-color-scheme: dark) {');
    lines.push('  :root {');
    for (const [role, value] of darkEntries) {
      lines.push(`    --color-${camelToKebab(role)}: ${value};`);
    }
    lines.push('  }');
    lines.push('}');
  }

  lines.push('');
  return lines.join('\n');
}

// ─── Helpers ────────────────────────────────────────────────

function camelToKebab(str) {
  return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

function quoteFontName(name) {
  return /\s/.test(name) ? `'${name}'` : name;
}
